# NOTE: We have not included the ELLIOT module itself in this repo. Please download this sperately
common_meta: &common_meta
  save_recs: False
  hyper_max_evals: 20
  hyper_opt_alg: tpe

training_meta: &training_meta
  epochs: 10
  batch_size: 128

experiment:
  dataset: movielens_1m_multilabel
  gpu: 1
  data_config:
    strategy: fixed
    train_path: ../data/movielens_1m_multilabel/0/train.tsv
    test_path: ../data/movielens_1m_multilabel/0/test.tsv
  models:
    MostPop:
      meta: *common_meta
      pop_ratio: 0.9 # As mentioned in the paper, this implementation of MostPop had been modified to ignore restrictions on repeat recommendations
    Random:
      meta: *common_meta
      random_seed: 42
    ProxyRecommender: # To evaluate more than one Proxy Recommender per row, the ELLIOT code needs to be modified slightly.
      name: TsetlinMachineNaive
      path: ../recs/movielens/tms/vanilla_tm_recs.tsv
    ProxyRecommender1:
      name: Graph Tsetlin Machine v6
      path: ../recs/movielens/tms/graphtm_movielens.tsv
    ItemKNN:
      meta: *common_meta
      neighbors: [50, 100]
      similarity: cosine
    MultiDAE:
      meta: *common_meta
      <<: *training_meta
      intermediate_dim: 600
      latent_dim: 200
      reg_lambda: 0.01
      lr: 0.001
      dropout_pkeep: 1
    UserKNN:
      meta: *common_meta
      neighbors: 40
      similarity: cosine
      implementation: aiolli
    SVDpp:
      meta: *common_meta
      <<: *training_meta
      factors: 50
      lr: 0.001
      reg_w: 0.1
      reg_b: 0.001
    NeuMF:
      meta: *common_meta
      <<: *training_meta
      mf_factors: 10
      mlp_factors: 10
      mlp_hidden_size: (64,32)
      lr: 0.001
      dropout: 0.0
      is_mf_train: True
      is_mlp_train: True
    BPRMF:
      meta: *common_meta
      <<: *training_meta
      factors: 10
      lr: 0.001
      bias_regularization: 0
      user_regularization: 0.0025
      positive_item_regularization: 0.0025
      negative_item_regularization: 0.0025
      update_negative_item_factors: True
      update_users: True
      update_items: True
      update_bias: True
  evaluation:
    simple_metrics: [nDCG, HR, Precision, Recall, F1, Gini, ARP, ItemCoverage]
  top_k: 10