#!/bin/bash
# This script is used to generate the devcontainer.json file from the template.
set -euo pipefail

TEMPLATE_FILE=".devcontainer/devcontainer.json.template"
OUTPUT_FILE=".devcontainer/devcontainer.json"

USER_ID=${USER_ID:-$(id -u)}
GROUP_ID=${GROUP_ID:-$(id -g)}
USER_NAME=${USER_NAME:-$(whoami)}
export USER_ID GROUP_ID USER_NAME

echo "Using USER_ID: $USER_ID, GROUP_ID: $GROUP_ID, USER_NAME: $USER_NAME"
envsubst '$USER_ID $GROUP_ID $USER_NAME' < "$TEMPLATE_FILE" > "$OUTPUT_FILE"